"""empty message

Revision ID: 4f130f1d59e6
Revises: 6452ad7d0e89
Create Date: 2019-02-27 21:37:05.413441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f130f1d59e6'
down_revision = '6452ad7d0e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'category')
    # ### end Alembic commands ###
